"""Real browser proof of the WebAuthn/hardware-backed Seven Keys credential UI
(WEBAUTHN_HARDWARE_CUSTODY.md): a Guardian and one seat register a real WebAuthn credential
through the actual rendered CredentialRegistrar UI and sign with it via the real
navigator.credentials API, backed by a Chrome DevTools Protocol virtual authenticator (real
ES256 keys, real CBOR/authenticatorData bytes generated by Chrome itself, real backend
verification) - not simulated in Python the way webauthn_hardware_custody_e2e.py's HTTP proof
is. This is the one script that actually exercises webauthn-signer.js's real
navigator.credentials.create()/get() calls; the HTTP E2E proves the wire protocol/crypto
end to end without a browser at all, and webauthn-signer.test.mjs proves webauthn-signer.js's
own pure functions in isolation. Together the three cover what none of them cover alone.
Only creates an isolated local development fixture tenant; no private key ever leaves the
(virtual, this-process-only) authenticator.
"""
import re
import uuid
from playwright.sync_api import sync_playwright, expect
from smoke import ROOT, request
from marketplace_browser_smoke import make_login
from community_references_e2e import MEMBER

def add_virtual_authenticator(page):
    """A CDP virtual authenticator: automaticPresenceSimulation means every
    navigator.credentials.create()/get() call resolves immediately as if a real key were
    tapped, isUserVerified=true means every ceremony reports user verification performed -
    exactly what CredentialRegistrar's requireUserVerification=true default asks for."""
    cdp=page.context.new_cdp_session(page)
    cdp.send('WebAuthn.enable',{'enableUI':False})
    cdp.send('WebAuthn.addVirtualAuthenticator',{'options':{'protocol':'ctap2','transport':'internal',
        'hasResidentKey':True,'hasUserVerification':True,'isUserVerified':True,'automaticPresenceSimulation':True}})

def main():
    admin=request('/api/shell/v1/auth/login','POST',{'email':'admin@stir.test',
        'password':(ROOT/'.local/secrets/login_password').read_text().strip()})['accessToken']
    suffix=uuid.uuid4().hex[:8]; name='WebAuthn UI '+suffix
    from multitenant import sql
    tenant=sql(f"select tenant_id from idax_core.tenant_create('webauthn-ui-{suffix}','{name}','active',false);")
    role=request(f'/api/shell/v1/tenants/{tenant}/roles','POST',{'key':'publisher'+suffix,'name':'Governance publisher','description':'Local browser test','enabled':True},admin,(200,201))
    request(f'/api/shell/v1/tenants/{tenant}/roles/'+role['id']+'/permissions','PUT',MEMBER+['stir.references.publish'],admin)
    ana_login=make_login(admin,tenant,role['id'],'ana',suffix)
    ana=request('/api/shell/v1/auth/login','POST',dict(zip(['email','password'],ana_login)))['accessToken']
    base=f'/api/stir/tenants/{tenant}'
    request(base+'/economic/marketplace/bootstrap','POST',{'communityName':name,'unitCode':'WAU','unitScale':2},ana)

    with sync_playwright() as pw:
        browser=pw.chromium.launch(channel='msedge',headless=True)
        errors=[]
        try:
            page=browser.new_context(locale='es-ES',viewport={'width':1440,'height':1400}).new_page()
            page.set_default_timeout(30000);page.on('pageerror',lambda e:errors.append(str(e)))
            add_virtual_authenticator(page)
            page.goto('http://localhost:8089')
            page.locator('input[type=email]').fill(ana_login[0]);page.locator('input[type=password]').fill(ana_login[1])
            page.locator('button[type=submit]').click()
            page.locator('.module-card').filter(has=page.get_by_role('heading',name='STIR',exact=True)).click()
            page.locator('.surface > header select').first.select_option(label=name)
            page.goto('http://localhost:8089/stir/governance')
            expect(page.get_by_text('Define sus siete asientos',exact=False)).to_be_visible()

            # --- Bootstrap: seats 1-6 and the Guardian stay the default same-device test
            # credential (already proven in governance_ui_browser.py); seat 7 registers a real
            # WebAuthn credential through the rendered radio choice + Register button, backed by
            # the CDP virtual authenticator added above. ---
            forms=page.locator('article.stir-form')
            expect(forms).to_have_count(8)
            for i in range(6):
                forms.nth(i).get_by_role('button',name='Generar una clave en este dispositivo',exact=True).click()
                expect(forms.nth(i).locator('code')).to_be_visible()
            seat7_form=forms.nth(6)
            seat7_form.get_by_text('Credencial WebAuthn / respaldada por hardware',exact=True).click()
            seat7_form.get_by_role('button',name='Registrar credencial de hardware',exact=True).click()
            expect(seat7_form.get_by_text('Credencial WebAuthn / respaldada por hardware',exact=True)).to_be_visible(timeout=15000)
            guardian_form=forms.nth(7)
            guardian_form.get_by_text('Credencial WebAuthn / respaldada por hardware',exact=True).click()
            guardian_form.get_by_role('button',name='Registrar credencial de hardware',exact=True).click()
            expect(guardian_form.get_by_text('Credencial WebAuthn / respaldada por hardware',exact=True)).to_be_visible(timeout=15000)

            page.get_by_role('button',name='Construir la carga de inicio',exact=True).click()
            expect(page.get_by_text('Carga completa de inicio',exact=True)).to_be_visible()
            sign_forms=page.locator('article.stir-form')
            expect(sign_forms).to_have_count(8)
            for i in range(6):
                sign_forms.nth(i).get_by_role('button',name='Firmar con la clave de este dispositivo',exact=True).click()
            sign_forms.nth(6).get_by_role('button',name='Firmar con WebAuthn',exact=True).click()
            sign_forms.nth(7).get_by_role('button',name='Firmar con WebAuthn',exact=True).click()
            expect(page.get_by_text('Se han reunido las ocho firmas.',exact=True)).to_be_visible(timeout=15000)
            page.get_by_role('button',name='Activar las siete llaves',exact=True).click()
            expect(page.get_by_role('heading',name='Gobernanza de las Siete Llaves',exact=True)).to_be_visible()
            for ordinal in range(1,8):
                expect(page.get_by_text(f'Asiento {ordinal}: ACTIVE',exact=False)).to_be_visible()
            expect(page.get_by_text('Version de la constitucion: 1',exact=False)).to_be_visible()
            print('PASS: mixed-credential bootstrap through the real UI - seat 7 and the Guardian '
                  'registered and signed with a real (CDP virtual) WebAuthn authenticator')

            # --- A second, later ceremony: an ordinary constitutional amendment, seat 7 and the
            # Guardian sign with WebAuthn AGAIN - proves a registered credential keeps working
            # across ceremonies (its authenticator sign_count genuinely advances each real use)
            # and that WebAuthn seats participate in ordinary governance identically to Ed25519
            # ones, entirely through the rendered UI. ---
            page.get_by_text('Proponer un cambio',exact=True).click()
            page.get_by_label('Observaciones mínimas',exact=True).fill('7')
            page.get_by_test_id('proposal-reason').fill('Raise the observation floor after review')
            page.get_by_test_id('proposal-submit').click()
            proposal=page.locator('article.stir-panel').filter(has_text='Enmendar la constitucion').first
            proposal.get_by_text('Firmas',exact=True).click()
            proposal.get_by_role('button',name='Cargar carga de firma',exact=True).click()
            for ordinal in range(1,7):
                proposal.get_by_role('button',name=f'Firmar con la clave de este dispositivo (Asiento {ordinal})',exact=True).click()
                expect(proposal.get_by_text(f'Asiento {ordinal}: Firma lista',exact=True)).to_be_visible()
            proposal.get_by_role('button',name='Firmar con WebAuthn (Asiento 7)',exact=True).click()
            expect(proposal.get_by_text('Asiento 7: Firma lista',exact=True)).to_be_visible(timeout=15000)
            proposal.locator('summary',has_text='Activar').click()
            proposal.get_by_role('button',name='Activar',exact=True).click()
            expect(page.get_by_text('Version de la constitucion: 2',exact=False)).to_be_visible()
            print('PASS: a real WebAuthn credential (CDP virtual authenticator) signed a second, '
                  'later ceremony and activated a real constitutional amendment through the UI')

            assert not errors,errors
            page.screenshot(path=str(ROOT/'.local/webauthn-hardware-custody-ui-final.png'),full_page=True)
            print('PASS BROWSER WEBAUTHN HARDWARE CUSTODY: real navigator.credentials.create()/get() '
                  'ceremonies via a CDP virtual authenticator, driven entirely through the rendered '
                  'CredentialRegistrar UI, for both a seat and the Guardian, across bootstrap and a '
                  'later constitutional amendment.')
        except Exception:
            page.screenshot(path=str(ROOT/'.local/webauthn-hardware-custody-ui-failure.png'),full_page=True)
            raise
        finally: browser.close()

if __name__=='__main__':main()
